<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>04-promise的链式调用(二)</title>
</head>
<body>
</body>

<script type="text/javascript">
	
	//网络请求 aaa -> 自己处理(10行)
	//处理: aaa111 -> 自己处理(10行)
	//处理: aaa222 -> 自己处理(10行)
	
/* 	new Promise((resolve, reject)=>{
		setTimeout(()=>{
			resolve('aaa')
		},1000)
		
	}).then(res => {
		console.log(res,'第一层的10行代码处理')
		
		return new Promise((resolve, reject) => {
				resolve('aaa'+111)
		})
		
	}).then(res => {
		console.log(res,'第二层的10行代码处理')
		
		return new Promise((resolve, reject) => {
				resolve('aaa'+222)
		})
		
	}).then(res => {
		console.log(res,'第三层的10行代码处理')
	}) */
	
	//new Promise(resolve => resolve(结果)) 简写
/* 	new Promise((resolve, reject)=>{
			setTimeout(()=>{
				resolve('aaa')
			},1000)
			
		}).then(res => {
			console.log(res,'第一层的10行代码处理')
			
			return Promise.resolve(res+111)
			
		}).then(res => {
			console.log(res,'第二层的10行代码处理')
			
			return Promise.resolve(res+222)		
		}).then(res => {
			console.log(res,'第三层的10行代码处理')
		}) */
		
	//再简写
	new Promise((resolve, reject)=>{
		setTimeout(()=>{
			resolve('aaa')
		},1000)
		
	}).then(res => {
		console.log(res,'第一层的10行代码处理')
		
		return res+111
		
	}).then(res => {
		console.log(res,'第二层的10行代码处理')
		
		throw 'err'
		return res+222
	}).then(res => {
		console.log(res,'第三层的10行代码处理')
	}).catch(err => {
		console.log(err,'返回错误处理')
	})
</script>
</html>
